CREATE TABLE IF NOT EXISTS S_DM_NODE (
	NODE_ID VARCHAR(16777216) COMMENT 'Unique identifier of node',
	NODE_NAME VARCHAR(16777216) COMMENT 'Name of node',
	OPERATING_POINT VARCHAR(16777216) COMMENT 'Name of operating point',
	SWITCH VARCHAR(16777216) COMMENT 'Name of the switch',
	SWITCH_POINT VARCHAR(16777216) COMMENT 'Name of the switch point',
	NORTH_LV95 NUMBER(10,3) COMMENT 'Coordinate north EPSG:2056 [m]',
	EAST_LV95 NUMBER(10,3) COMMENT 'Coordinate east EPSG:2056 [m]',
	HEIGHT_LV95 NUMBER(10,3) COMMENT 'Coordinate height EPSG:2056 [m]',
	LATITUDE_ETRS89 NUMBER(12,9) COMMENT 'Latitude EPSG:4258 [deg]',
	LONGITUDE_ETRS89 NUMBER(12,9) COMMENT 'Longitude EPSG:4258 [deg]',
	ALTITUDE_ETRS89 NUMBER(10,3) COMMENT 'Altitude EPSG:4258 [deg]',
	VALID_FROM TIMESTAMP_NTZ(6) COMMENT 'Local date valid from',
	VALID_TO TIMESTAMP_NTZ(6) COMMENT 'Local valid to',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(6) COMMENT 'Timestamp of the row creation'
)
COMMENT='Standardization table for track node'
;