name: Write table definitions to README

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'sql/*.sql'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Write tables to README
        run: |
          # replace README with template
          cp ./helpers/template_README.md ./README.md
          # iterate over sql files and write to README.md
          for file in "sql"/*; do
            if [ -f "$file" ]; then
              python3 ./helpers/insert2readme.py $file ./README.md
            fi
          done

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "updated README with newest table definitions"
          git push